//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLoader
{
    using System;
    using System.Collections.Generic;
    
    public partial class CriticSite
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CriticSite()
        {
            this.CriticRatings = new HashSet<CriticRating>();
            this.CriticRatingLoaders = new HashSet<CriticRatingLoader>();
        }
    
        public int CriticSiteId { get; set; }
        public string SiteName { get; set; }
        public string WebUrl { get; set; }
        public Nullable<int> AlexaRating { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CriticRating> CriticRatings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CriticRatingLoader> CriticRatingLoaders { get; set; }
    }
}
