//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLoader
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataLoaderEntities : DbContext
    {
        public DataLoaderEntities()
            : base("name=DataLoaderEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CriticRating> CriticRatings { get; set; }
        public virtual DbSet<CriticRatingLoader> CriticRatingLoaders { get; set; }
        public virtual DbSet<CriticSite> CriticSites { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<Movie> Movies { get; set; }
        public virtual DbSet<MovieDetail> MovieDetails { get; set; }
        public virtual DbSet<MovieDetailLoader> MovieDetailLoaders { get; set; }
        public virtual DbSet<MovieLoader> MovieLoaders { get; set; }
        public virtual DbSet<UserRating> UserRatings { get; set; }
        public virtual DbSet<UserRatingLoader> UserRatingLoaders { get; set; }
    }
}
