//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLoader
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieDetailLoader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MovieDetailLoader()
        {
            this.CriticRatingLoaders = new HashSet<CriticRatingLoader>();
            this.UserRatingLoaders = new HashSet<UserRatingLoader>();
        }
    
        public int MovieDetailID { get; set; }
        public int MovieID { get; set; }
        public string DetailsUrl { get; set; }
        public string GalleryUrl { get; set; }
        public string TraillerUrl { get; set; }
        public string ScheduleUrl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CriticRatingLoader> CriticRatingLoaders { get; set; }
        public virtual MovieLoader MovieLoader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRatingLoader> UserRatingLoaders { get; set; }
    }
}
