//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLoader
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieLoader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MovieLoader()
        {
            this.MovieDetailLoaders = new HashSet<MovieDetailLoader>();
        }
    
        public int MovieID { get; set; }
        public string Name { get; set; }
        public string SmallPictureUrl { get; set; }
        public string LargePictureUrl { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public int LanguageID { get; set; }
    
        public virtual Language Language { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieDetailLoader> MovieDetailLoaders { get; set; }
    }
}
