//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLoader
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRatingLoader
    {
        public int UserRatingId { get; set; }
        public int MovieDetailID { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public int NumberOfUsers { get; set; }
    
        public virtual MovieDetailLoader MovieDetailLoader { get; set; }
    }
}
