//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManhattan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Artist()
        {
            this.MovieArtists = new HashSet<MovieArtist>();
            this.MoviePhotoArtists = new HashSet<MoviePhotoArtist>();
            this.MovieSongArtists = new HashSet<MovieSongArtist>();
        }
    
        public int ArtistId { get; set; }
        public string ArtistName { get; set; }
        public Nullable<System.DateTime> ArtistDOB { get; set; }
        public string ArtistTitle { get; set; }
        public string ArtistNickName { get; set; }
        public int ArtistTypeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieArtist> MovieArtists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MoviePhotoArtist> MoviePhotoArtists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieSongArtist> MovieSongArtists { get; set; }
        public virtual ArtistType ArtistType { get; set; }
    }
}
