//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManhattan.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectManhattanEntities : DbContext
    {
        public ProjectManhattanEntities()
            : base("name=ProjectManhattanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artist> Artists { get; set; }
        public virtual DbSet<ArtistType> ArtistTypes { get; set; }
        public virtual DbSet<CriticMovieRating> CriticMovieRatings { get; set; }
        public virtual DbSet<Critic> Critics { get; set; }
        public virtual DbSet<Distributor> Distributors { get; set; }
        public virtual DbSet<Finance> Finances { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<MovieArtist> MovieArtists { get; set; }
        public virtual DbSet<MovieDistributor> MovieDistributors { get; set; }
        public virtual DbSet<MoviePhotoArtist> MoviePhotoArtists { get; set; }
        public virtual DbSet<MoviePhoto> MoviePhotoes { get; set; }
        public virtual DbSet<Movie> Movies { get; set; }
        public virtual DbSet<MovieSongArtist> MovieSongArtists { get; set; }
        public virtual DbSet<MovieSong> MovieSongs { get; set; }
        public virtual DbSet<MovieTrailer> MovieTrailers { get; set; }
        public virtual DbSet<Schedule> Schedules { get; set; }
        public virtual DbSet<Theatre> Theatres { get; set; }
        public virtual DbSet<UserPreference> UserPreferences { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserMovieRating> UserMovieRatings { get; set; }
    }
}
