//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManhattan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMovieRating
    {
        public int UserMovieRatingId { get; set; }
        public int UserId { get; set; }
        public int MovieId { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public string ReviewDescription { get; set; }
        public System.DateTime RatingDate { get; set; }
    
        public virtual Movie Movie { get; set; }
    }
}
