//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projectmanhattan.Client.DL {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UrlResourceFile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UrlResourceFile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Projectmanhattan.Client.DL.UrlResourceFile", typeof(UrlResourceFile).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://projectmanhattan-api-dev.azurewebsites.net/api/.
        /// </summary>
        internal static string BasePath {
            get {
                return ResourceManager.GetString("BasePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /NowPlaying?MovieID={0}.
        /// </summary>
        internal static string MovieDetail {
            get {
                return ResourceManager.GetString("MovieDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /HomeScreen.
        /// </summary>
        internal static string MovieSummary {
            get {
                return ResourceManager.GetString("MovieSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Homescreen?searchString={0}.
        /// </summary>
        internal static string MovieSummarySeacrh {
            get {
                return ResourceManager.GetString("MovieSummarySeacrh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Trailers?MovieID={0}.
        /// </summary>
        internal static string MovieTrailer {
            get {
                return ResourceManager.GetString("MovieTrailer", resourceCulture);
            }
        }
    }
}
